### ISSUE TITLE
安装环境咨询 Installation environment consultation

### ISSUE THREAD

**Issue by SMY19999** [dendenxu/torchxpbd#1]
作者你好！我最近尝试配置环境来运行这份代码，但是在import pytorch3d时总报错，ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory.
请问你方便提供一下torch相关的版本吗？
python, torch, pytorch3d, torch_scatter

**Comment by dendenxu** [comment]
你好，或许你可以试试直接从github编译并安装pytorch3d: `pip install git+https://github.com/facebookresearch/pytorch3d`. 我并没有锁定具体的包版本，印象里代码里并没有使用特殊版本的功能。这是我常用环境中的包版本：
```shell
Python 3.10.9
---
Name: torch
Version: 1.13.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
---
Name: torch-scatter
Version: 2.1.0
Summary: PyTorch Extension Library of Optimized Scatter Operations
Home-page: https://github.com/rusty1s/pytorch_scatter
Author: Matthias Fey
Author-email: matthias.fey@tu-dortmund.de
License:
---
Name: pytorch3d
Version: 0.7.2
Summary: PyTorch3D is FAIR's library of reusable components for deep Learning with 3D data.
Home-page: https://github.com/facebookresearch/pytorch3d
Author: FAIR
Author-email:
License:
```

**Comment by SMY19999** [comment]
好的，非常感谢！
我刚刚发现是我安装torch和pytorch3d方法的问题，我习惯性用pip安装的torch, 又用conda安装的pytorch3d，所以有些问题。
我的版本是python 3.8, torch 1.12.1+cu113, pytorch3d 0.7.5。
刚刚成功运行了你的代码！非常酷！

**Comment by dendenxu** [comment]
👍🏼 很高兴能帮到你
